apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-pipeline-config

data:
  logstash.conf: |
    input {
      jdbc {
        jdbc_driver_library => "/usr/share/logstash/logstash-core/lib/jars/mysql-connector-java.jar"
        jdbc_driver_class => "com.mysql.jdbc.Driver"
        jdbc_connection_string => "jdbc:mysql://mysql-service:3306/${MYSQL_DATABASE}"
        jdbc_user => "${MYSQL_USER}"
        jdbc_password => "${MYSQL_PASSWORD}"
        schedule => "* * * * *"
        statement => "SELECT * FROM your_table WHERE updated_at > :sql_last_value"
        use_column_value => true
        tracking_column => "updated_at"
        tracking_column_type => "timestamp"
      }
    }

    filter {
    
    }

    output {
      elasticsearch {
        hosts => ["elasticsearch-service:9200"]
        index => "your-index-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }
