spring:
  application:
    name: asset

  profiles:
    group:
      local:
        - secret

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:image-db
    username: sa
    password:
    driver-class-name: org.h2.Driver


  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  h2:
    console:
      path: /h2-console
      enabled: true

logging:
  level:
    io.awspring.cloud: DEBUG

custom:

  image:
    allowed-extension: jpg,jpeg,png,webp
    max-size: 10485760 # 10mb