spring:
  application:
    name: Image

  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:h2:mem:image-db
    username: sa
    password:
    driver-class-name: org.h2.Driver



  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    io.awspring.cloud: DEBUG

custom:
  bucket-name:
  image:
    allowed-extension: jpg, jpeg, png
    max-size: 10485760 # 10mb